package com.educareapps.jsonreader.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TASK_PACK".
 */
public class TaskPack {

    private Long id;
    /** Not-null value. */
    private String name;
    private Integer lessonNumber;
    private int ageRange;
    /** Not-null value. */
    private String Description;
    private java.util.Date createdAt;
    private Boolean state;
    private String type;

    public TaskPack() {
    }

    public TaskPack(Long id) {
        this.id = id;
    }

    public TaskPack(Long id, String name, Integer lessonNumber, int ageRange, String Description, java.util.Date createdAt, Boolean state, String type) {
        this.id = id;
        this.name = name;
        this.lessonNumber = lessonNumber;
        this.ageRange = ageRange;
        this.Description = Description;
        this.createdAt = createdAt;
        this.state = state;
        this.type = type;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    public Integer getLessonNumber() {
        return lessonNumber;
    }

    public void setLessonNumber(Integer lessonNumber) {
        this.lessonNumber = lessonNumber;
    }

    public int getAgeRange() {
        return ageRange;
    }

    public void setAgeRange(int ageRange) {
        this.ageRange = ageRange;
    }

    /** Not-null value. */
    public String getDescription() {
        return Description;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDescription(String Description) {
        this.Description = Description;
    }

    public java.util.Date getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(java.util.Date createdAt) {
        this.createdAt = createdAt;
    }

    public Boolean getState() {
        return state;
    }

    public void setState(Boolean state) {
        this.state = state;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

}
