package com.educareapps.jsonreader.dao;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.educareapps.jsonreader.dao.Task;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TASK".
*/
public class TaskDao extends AbstractDao<Task, Long> {

    public static final String TABLENAME = "TASK";

    /**
     * Properties of entity Task.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "ID");
        public final static Property UniqId = new Property(1, long.class, "uniqId", false, "UNIQ_ID");
        public final static Property Name = new Property(2, String.class, "name", false, "NAME");
        public final static Property TaskImage = new Property(3, String.class, "taskImage", false, "TASK_IMAGE");
        public final static Property Type = new Property(4, String.class, "type", false, "TYPE");
        public final static Property BackgroundColor = new Property(5, int.class, "backgroundColor", false, "BACKGROUND_COLOR");
        public final static Property BackgroundImage = new Property(6, String.class, "backgroundImage", false, "BACKGROUND_IMAGE");
        public final static Property SlideSequence = new Property(7, int.class, "slideSequence", false, "SLIDE_SEQUENCE");
        public final static Property Active = new Property(8, Boolean.class, "active", false, "ACTIVE");
        public final static Property CreatedAt = new Property(9, java.util.Date.class, "createdAt", false, "CREATED_AT");
        public final static Property UpdatedAt = new Property(10, java.util.Date.class, "updatedAt", false, "UPDATED_AT");
        public final static Property TaskPackId = new Property(11, Long.class, "taskPackId", false, "TASK_PACK_ID");
        public final static Property FeedbackImage = new Property(12, String.class, "feedbackImage", false, "FEEDBACK_IMAGE");
        public final static Property FeedbackAnimation = new Property(13, int.class, "feedbackAnimation", false, "FEEDBACK_ANIMATION");
        public final static Property PositiveAnimation = new Property(14, int.class, "positiveAnimation", false, "POSITIVE_ANIMATION");
        public final static Property NegativeAnimation = new Property(15, int.class, "negativeAnimation", false, "NEGATIVE_ANIMATION");
        public final static Property FeedbackSound = new Property(16, String.class, "feedbackSound", false, "FEEDBACK_SOUND");
        public final static Property PositiveSound = new Property(17, String.class, "positiveSound", false, "POSITIVE_SOUND");
        public final static Property NegativeSound = new Property(18, String.class, "negativeSound", false, "NEGATIVE_SOUND");
        public final static Property FeedbackType = new Property(19, int.class, "feedbackType", false, "FEEDBACK_TYPE");
        public final static Property Tutorial = new Property(20, int.class, "tutorial", false, "TUTORIAL");
        public final static Property Transition = new Property(21, int.class, "transition", false, "TRANSITION");
        public final static Property ErrorBgColor = new Property(22, int.class, "errorBgColor", false, "ERROR_BG_COLOR");
        public final static Property ErrorImage = new Property(23, String.class, "errorImage", false, "ERROR_IMAGE");
        public final static Property Errortext = new Property(24, String.class, "errortext", false, "ERRORTEXT");
        public final static Property ErrorMandatoryScreen = new Property(25, int.class, "errorMandatoryScreen", false, "ERROR_MANDATORY_SCREEN");
        public final static Property SequenceText = new Property(26, String.class, "sequenceText", false, "SEQUENCE_TEXT");
        public final static Property Template = new Property(27, int.class, "template", false, "TEMPLATE");
        public final static Property TaskExtraOne = new Property(28, int.class, "taskExtraOne", false, "TASK_EXTRA_ONE");
        public final static Property TaskExtraTwo = new Property(29, Integer.class, "taskExtraTwo", false, "TASK_EXTRA_TWO");
        public final static Property TaskExtraThree = new Property(30, String.class, "taskExtraThree", false, "TASK_EXTRA_THREE");
        public final static Property TaskExtraFour = new Property(31, String.class, "taskExtraFour", false, "TASK_EXTRA_FOUR");
        public final static Property TaskExtraFive = new Property(32, Integer.class, "taskExtraFive", false, "TASK_EXTRA_FIVE");
        public final static Property Bubble = new Property(33, Integer.class, "bubble", false, "BUBBLE");
        public final static Property UserId = new Property(34, long.class, "userId", false, "USER_ID");
    };

    private DaoSession daoSession;

    private Query<Task> user_TasksQuery;

    public TaskDao(DaoConfig config) {
        super(config);
    }
    
    public TaskDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TASK\" (" + //
                "\"ID\" INTEGER PRIMARY KEY ," + // 0: id
                "\"UNIQ_ID\" INTEGER NOT NULL ," + // 1: uniqId
                "\"NAME\" TEXT NOT NULL ," + // 2: name
                "\"TASK_IMAGE\" TEXT NOT NULL ," + // 3: taskImage
                "\"TYPE\" TEXT NOT NULL ," + // 4: type
                "\"BACKGROUND_COLOR\" INTEGER NOT NULL ," + // 5: backgroundColor
                "\"BACKGROUND_IMAGE\" TEXT," + // 6: backgroundImage
                "\"SLIDE_SEQUENCE\" INTEGER NOT NULL ," + // 7: slideSequence
                "\"ACTIVE\" INTEGER," + // 8: active
                "\"CREATED_AT\" INTEGER," + // 9: createdAt
                "\"UPDATED_AT\" INTEGER," + // 10: updatedAt
                "\"TASK_PACK_ID\" INTEGER," + // 11: taskPackId
                "\"FEEDBACK_IMAGE\" TEXT NOT NULL ," + // 12: feedbackImage
                "\"FEEDBACK_ANIMATION\" INTEGER NOT NULL ," + // 13: feedbackAnimation
                "\"POSITIVE_ANIMATION\" INTEGER NOT NULL ," + // 14: positiveAnimation
                "\"NEGATIVE_ANIMATION\" INTEGER NOT NULL ," + // 15: negativeAnimation
                "\"FEEDBACK_SOUND\" TEXT NOT NULL ," + // 16: feedbackSound
                "\"POSITIVE_SOUND\" TEXT NOT NULL ," + // 17: positiveSound
                "\"NEGATIVE_SOUND\" TEXT NOT NULL ," + // 18: negativeSound
                "\"FEEDBACK_TYPE\" INTEGER NOT NULL ," + // 19: feedbackType
                "\"TUTORIAL\" INTEGER NOT NULL ," + // 20: tutorial
                "\"TRANSITION\" INTEGER NOT NULL ," + // 21: transition
                "\"ERROR_BG_COLOR\" INTEGER NOT NULL ," + // 22: errorBgColor
                "\"ERROR_IMAGE\" TEXT NOT NULL ," + // 23: errorImage
                "\"ERRORTEXT\" TEXT NOT NULL ," + // 24: errortext
                "\"ERROR_MANDATORY_SCREEN\" INTEGER NOT NULL ," + // 25: errorMandatoryScreen
                "\"SEQUENCE_TEXT\" TEXT NOT NULL ," + // 26: sequenceText
                "\"TEMPLATE\" INTEGER NOT NULL ," + // 27: template
                "\"TASK_EXTRA_ONE\" INTEGER NOT NULL ," + // 28: taskExtraOne
                "\"TASK_EXTRA_TWO\" INTEGER," + // 29: taskExtraTwo
                "\"TASK_EXTRA_THREE\" TEXT," + // 30: taskExtraThree
                "\"TASK_EXTRA_FOUR\" TEXT," + // 31: taskExtraFour
                "\"TASK_EXTRA_FIVE\" INTEGER," + // 32: taskExtraFive
                "\"BUBBLE\" INTEGER," + // 33: bubble
                "\"USER_ID\" INTEGER NOT NULL );"); // 34: userId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TASK\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Task entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getUniqId());
        stmt.bindString(3, entity.getName());
        stmt.bindString(4, entity.getTaskImage());
        stmt.bindString(5, entity.getType());
        stmt.bindLong(6, entity.getBackgroundColor());
 
        String backgroundImage = entity.getBackgroundImage();
        if (backgroundImage != null) {
            stmt.bindString(7, backgroundImage);
        }
        stmt.bindLong(8, entity.getSlideSequence());
 
        Boolean active = entity.getActive();
        if (active != null) {
            stmt.bindLong(9, active ? 1L: 0L);
        }
 
        java.util.Date createdAt = entity.getCreatedAt();
        if (createdAt != null) {
            stmt.bindLong(10, createdAt.getTime());
        }
 
        java.util.Date updatedAt = entity.getUpdatedAt();
        if (updatedAt != null) {
            stmt.bindLong(11, updatedAt.getTime());
        }
 
        Long taskPackId = entity.getTaskPackId();
        if (taskPackId != null) {
            stmt.bindLong(12, taskPackId);
        }
        stmt.bindString(13, entity.getFeedbackImage());
        stmt.bindLong(14, entity.getFeedbackAnimation());
        stmt.bindLong(15, entity.getPositiveAnimation());
        stmt.bindLong(16, entity.getNegativeAnimation());
        stmt.bindString(17, entity.getFeedbackSound());
        stmt.bindString(18, entity.getPositiveSound());
        stmt.bindString(19, entity.getNegativeSound());
        stmt.bindLong(20, entity.getFeedbackType());
        stmt.bindLong(21, entity.getTutorial());
        stmt.bindLong(22, entity.getTransition());
        stmt.bindLong(23, entity.getErrorBgColor());
        stmt.bindString(24, entity.getErrorImage());
        stmt.bindString(25, entity.getErrortext());
        stmt.bindLong(26, entity.getErrorMandatoryScreen());
        stmt.bindString(27, entity.getSequenceText());
        stmt.bindLong(28, entity.getTemplate());
        stmt.bindLong(29, entity.getTaskExtraOne());
 
        Integer taskExtraTwo = entity.getTaskExtraTwo();
        if (taskExtraTwo != null) {
            stmt.bindLong(30, taskExtraTwo);
        }
 
        String taskExtraThree = entity.getTaskExtraThree();
        if (taskExtraThree != null) {
            stmt.bindString(31, taskExtraThree);
        }
 
        String taskExtraFour = entity.getTaskExtraFour();
        if (taskExtraFour != null) {
            stmt.bindString(32, taskExtraFour);
        }
 
        Integer taskExtraFive = entity.getTaskExtraFive();
        if (taskExtraFive != null) {
            stmt.bindLong(33, taskExtraFive);
        }
 
        Integer bubble = entity.getBubble();
        if (bubble != null) {
            stmt.bindLong(34, bubble);
        }
        stmt.bindLong(35, entity.getUserId());
    }

    @Override
    protected void attachEntity(Task entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Task readEntity(Cursor cursor, int offset) {
        Task entity = new Task( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // uniqId
            cursor.getString(offset + 2), // name
            cursor.getString(offset + 3), // taskImage
            cursor.getString(offset + 4), // type
            cursor.getInt(offset + 5), // backgroundColor
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // backgroundImage
            cursor.getInt(offset + 7), // slideSequence
            cursor.isNull(offset + 8) ? null : cursor.getShort(offset + 8) != 0, // active
            cursor.isNull(offset + 9) ? null : new java.util.Date(cursor.getLong(offset + 9)), // createdAt
            cursor.isNull(offset + 10) ? null : new java.util.Date(cursor.getLong(offset + 10)), // updatedAt
            cursor.isNull(offset + 11) ? null : cursor.getLong(offset + 11), // taskPackId
            cursor.getString(offset + 12), // feedbackImage
            cursor.getInt(offset + 13), // feedbackAnimation
            cursor.getInt(offset + 14), // positiveAnimation
            cursor.getInt(offset + 15), // negativeAnimation
            cursor.getString(offset + 16), // feedbackSound
            cursor.getString(offset + 17), // positiveSound
            cursor.getString(offset + 18), // negativeSound
            cursor.getInt(offset + 19), // feedbackType
            cursor.getInt(offset + 20), // tutorial
            cursor.getInt(offset + 21), // transition
            cursor.getInt(offset + 22), // errorBgColor
            cursor.getString(offset + 23), // errorImage
            cursor.getString(offset + 24), // errortext
            cursor.getInt(offset + 25), // errorMandatoryScreen
            cursor.getString(offset + 26), // sequenceText
            cursor.getInt(offset + 27), // template
            cursor.getInt(offset + 28), // taskExtraOne
            cursor.isNull(offset + 29) ? null : cursor.getInt(offset + 29), // taskExtraTwo
            cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30), // taskExtraThree
            cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31), // taskExtraFour
            cursor.isNull(offset + 32) ? null : cursor.getInt(offset + 32), // taskExtraFive
            cursor.isNull(offset + 33) ? null : cursor.getInt(offset + 33), // bubble
            cursor.getLong(offset + 34) // userId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Task entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUniqId(cursor.getLong(offset + 1));
        entity.setName(cursor.getString(offset + 2));
        entity.setTaskImage(cursor.getString(offset + 3));
        entity.setType(cursor.getString(offset + 4));
        entity.setBackgroundColor(cursor.getInt(offset + 5));
        entity.setBackgroundImage(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setSlideSequence(cursor.getInt(offset + 7));
        entity.setActive(cursor.isNull(offset + 8) ? null : cursor.getShort(offset + 8) != 0);
        entity.setCreatedAt(cursor.isNull(offset + 9) ? null : new java.util.Date(cursor.getLong(offset + 9)));
        entity.setUpdatedAt(cursor.isNull(offset + 10) ? null : new java.util.Date(cursor.getLong(offset + 10)));
        entity.setTaskPackId(cursor.isNull(offset + 11) ? null : cursor.getLong(offset + 11));
        entity.setFeedbackImage(cursor.getString(offset + 12));
        entity.setFeedbackAnimation(cursor.getInt(offset + 13));
        entity.setPositiveAnimation(cursor.getInt(offset + 14));
        entity.setNegativeAnimation(cursor.getInt(offset + 15));
        entity.setFeedbackSound(cursor.getString(offset + 16));
        entity.setPositiveSound(cursor.getString(offset + 17));
        entity.setNegativeSound(cursor.getString(offset + 18));
        entity.setFeedbackType(cursor.getInt(offset + 19));
        entity.setTutorial(cursor.getInt(offset + 20));
        entity.setTransition(cursor.getInt(offset + 21));
        entity.setErrorBgColor(cursor.getInt(offset + 22));
        entity.setErrorImage(cursor.getString(offset + 23));
        entity.setErrortext(cursor.getString(offset + 24));
        entity.setErrorMandatoryScreen(cursor.getInt(offset + 25));
        entity.setSequenceText(cursor.getString(offset + 26));
        entity.setTemplate(cursor.getInt(offset + 27));
        entity.setTaskExtraOne(cursor.getInt(offset + 28));
        entity.setTaskExtraTwo(cursor.isNull(offset + 29) ? null : cursor.getInt(offset + 29));
        entity.setTaskExtraThree(cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30));
        entity.setTaskExtraFour(cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31));
        entity.setTaskExtraFive(cursor.isNull(offset + 32) ? null : cursor.getInt(offset + 32));
        entity.setBubble(cursor.isNull(offset + 33) ? null : cursor.getInt(offset + 33));
        entity.setUserId(cursor.getLong(offset + 34));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Task entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Task entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "tasks" to-many relationship of User. */
    public List<Task> _queryUser_Tasks(long userId) {
        synchronized (this) {
            if (user_TasksQuery == null) {
                QueryBuilder<Task> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.UserId.eq(null));
                user_TasksQuery = queryBuilder.build();
            }
        }
        Query<Task> query = user_TasksQuery.forCurrentThread();
        query.setParameter(0, userId);
        return query.list();
    }

}
